### ISSUE TITLE
struct flock fl = {0};

### ISSUE THREAD

**Issue by gddg** [gavv/snippets#3] opened 2019-06-13 09:07 UTC
https://github.com/gavv/snippets/blob/1913933ca46781ae0f323f95af9d514bc2ffb818/fs/locks.c#L71

struct flock fl = {0};
fcntl: Invalid argument.

**Comment by gavv** [comment] 2019-06-22 07:48
Could you please be more specific? Did you encounter a bug?

**Comment by gddg** [comment] 2019-07-05 01:27
I run the program at test_fcntl_posix(int fd) method result is error Invalid argument.
Because you haven't init struct flock  all memory space. 
ubuntu16 , X64

**Comment by gavv** [comment] 2019-07-27 11:30
Thanks and sorry for late reply.

> I run the program at test_fcntl_posix(int fd) 

Are you sure that it was `fcntl_posix`, not `fcntl_linux`?

Because it seems that:

* the uninitialized field is l_pid

* F_SETLK(W) (POSIX record locks) ignores l_pid and thus it may be left uninitialized; this is confirmed by "Locking and Unlocking a File" example [here](http://pubs.opengroup.org/onlinepubs/9699919799/functions/fcntl.html)

* F_OFD_SETLK(W) (Open file description locks) requires l_pid to be zero; this is stated [here](http://man7.org/linux/man-pages/man2/fcntl.2.html): "EINVAL cmd is F_OFD_SETLK, F_OFD_SETLKW, or F_OFD_GETLK, and l_pid
              was not specified as zero."

Tested it on Ubuntu 16.04 and it seems that it's true.

I've fixed the test program and the blog post according to this.

**Comment by gavv** [comment] 2019-08-07 20:19
I think this is fixed, so I'm closing this; feel free to reopen.

**Closed as completed by gavv** 2019-08-07 20:19 UTC
